### ISSUE TITLE
As a developer, I can consume a plant API endpoints to get the following information for each plant in a garden:

### ISSUE THREAD

**Issue by AngelaGuardia** [My-Solar-Garden/microservice#1]
- Recommended soil moisture levels
- Recommended light exposure
- Recommended temperature range
https://docs.trefle.io/docs/advanced/plants-fields/#growth

- Another API that could be used 
https://harvesthelper.herokuapp.com
<img width="1072" alt="Screen Shot 2020-10-26 at 4 54 20 PM" src="https://user-images.githubusercontent.com/61212296/97232837-e7c18d00-17ab-11eb-86a4-525ea32f3e81.png">
Screenshot from postman

## tasks:

- [x] Consume API + tests
- [x] Expose API + tests
- [ ] API exposure sad path testing
- [x] Deploy to Heroku
- [x] Integrate Travis CI
- [x] Implement webmock + VCR
- [x] Create README

** Figure out env var issue
